name: Build and Test Locust

on:
  pull_request:
#  push:
#    branches: [main, develop]
#    tags: ['*']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMG_BASE_REPO: project8/luna_base
  IMG_BASE_TAG: v1.3.0
  KASS_REPO: project8/kassiopeia
  KASS_TAG: v3.7.7
#  locust_mc_BUILD_WITH_KASSIOPEIA: ON
#  locust_mc_ENABLE_EXECUTABLES: ON
  NARG: 2
#  locust_mc_ENABLE_TESTING: ON
#  locust_mc_BUILD_TYPE: Debug
#  locust_mc_TAG: test

jobs:

  docker-build-and-publish:

    name: Build and push the docker images

    strategy:
      matrix:
        build: [Dev, Prod]
        fail-fast: [false]
        include:
          - build: Dev
            tag-suffix: '-dev'
            build-type: Debug
            build-tests: true
          - build: Prod
            tag-suffix: ''
            build-type: Release
            build-tests: false

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout builder repo
        uses: actions/checkout@v3

      - name: Check out Kassiopeia
        uses: actions/checkout@v3
        with:
          repository: ${{ env.KASS_REPO }}
          ref: ${{ env.KASS_TAG }}
          submodules: recursive
          fetch-depth: 0
          path: kassiopeia

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          flavor: |
            latest=auto
            suffix=${{ matrix.tag-suffix }},onlatest=true
          tags: |
            type=raw,value=${{ env.KASS_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: print things
        run: |
          echo "docker_meta.outputs.tags: ${{ steps.docker_meta.outputs.tags }}"
          echo "base image: ${{ env.REGISTRY }}/${{ env.BASE_IMG_REPO }}:${{ env.IMG_BASE_TAG }}"
          echo "build-type: ${{ matrix.build-type }}"
          echo "narg: ${{ env.NARG }}"

      - name: Build Kassiopeia
        id: build-kass
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          load: false
          build-args: |
            img_repo=${{ env.REGISTRY }}/${{ env.BASE_IMG_REPO }}
            img_tag=${{ env.IMG_BASE_TAG }}-dev
            final_img_repo=${{ env.REGISTRY }}/${{ env.BASE_IMG_REPO }}
            final_img_tag=${{ env.IMG_BASE_TAG }}${{ matrix.tag-suffix }}
            build_type=${{ matrix.build-type }}
            narg=${{ env.NARG }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          platforms: linux/amd64


# For debugging
      - name: Setup tmate session
        if: ${{ ! success() }}
        uses: mxschmitt/action-tmate@v3

